<?php
/**
 * Cloud Storage Helper untuk QR Codes
 * Karena Vercel filesystem read-only, gunakan cloud storage
 */

class CloudQRStorage {
    
    /**
     * Generate QR Code menggunakan service external
     */
    public static function generateQRCode($kode_unik) {
        // Option 1: QR Server API (reliable)
        $qr_url = "https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=" . urlencode($kode_unik);
        
        // Option 2: Alternative API
        // $qr_url = "https://quickchart.io/qr?text=" . urlencode($kode_unik) . "&size=200";
        
        return $qr_url;
    }
    
    /**
     * Get QR Code as base64 untuk embed langsung
     */
    public static function getQRCodeBase64($kode_unik) {
        $qr_url = self::generateQRCode($kode_unik);
        
        $context = stream_context_create([
            'http' => [
                'timeout' => 10,
                'user_agent' => 'Mozilla/5.0 (compatible; QR-Generator/1.0)'
            ]
        ]);
        
        $image_data = @file_get_contents($qr_url, false, $context);
        
        if ($image_data && strlen($image_data) > 100) {
            return 'data:image/png;base64,' . base64encode($image_data);
        }
        
        return null;
    }
    
    /**
     * Generate SVG QR fallback
     */
    public static function generateSVGFallback($kode_unik) {
        return '<?xml version="1.0" encoding="UTF-8"?>
<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
  <rect width="200" height="200" fill="white" stroke="#ccc" stroke-width="1"/>
  <rect x="20" y="20" width="160" height="160" fill="none" stroke="black" stroke-width="2"/>
  <text x="100" y="85" text-anchor="middle" font-family="monospace" font-size="14" fill="black" font-weight="bold">' . $kode_unik . '</text>
  <text x="100" y="110" text-anchor="middle" font-family="Arial" font-size="12" fill="gray">QR Code</text>
  <text x="100" y="130" text-anchor="middle" font-family="Arial" font-size="10" fill="gray">Scan dengan aplikasi</text>
  <text x="100" y="150" text-anchor="middle" font-family="Arial" font-size="8" fill="#999">Generated by Orior</text>
</svg>';
    }
    
    /**
     * Upload ke Cloudinary (optional - membutuhkan API key)
     */
    public static function uploadToCloudinary($image_data, $filename) {
        // Implementasi upload ke Cloudinary jika diperlukan
        // Membutuhkan CLOUDINARY_URL environment variable
        
        $cloudinary_url = $_ENV['CLOUDINARY_URL'] ?? getenv('CLOUDINARY_URL');
        if (!$cloudinary_url) {
            return false;
        }
        
        // Implement Cloudinary upload API call here
        // Return public URL if successful
        
        return false; // Placeholder
    }
}
?>